import avatar1 from "@root/assets/svg/avatar1.svg";
import avatar2 from "@root/assets/svg/avatar2.svg";
import avatar3 from "@root/assets/svg/avatar3.svg";
import avatar4 from "@root/assets/svg/avatar4.svg";
import avatar5 from "@root/assets/svg/avatar5.svg";
import avatar6 from "@root/assets/svg/avatar6.svg";
import avatar7 from "@root/assets/svg/avatar7.svg";

export const avatarsData: any = [
  {
    id: 1,
    image: avatar1,
    name: "Usman Saeed",
    shortName: "US",
    textColor: "#0E918C",
    desgination: "CEO",
    description: `Usman Saeed is an accomplished leader and visionary CEO with a diverse background that brings a unique blend of skills and experiences to Legal Help Squad. His portfolio showcases his ability to drive innovation, foster growth, and lead strategic initiatives across industries`,
    facebook: "#",
    twitter: "#",
    instagram: "#",
    boxShadow: "rgba(14, 145, 140, 0.36)",
    circleColor: "rgba(14, 145, 140, 0.18)",
  },
  {
    id: 2,
    image: avatar2,
    name: "Haji Yunis",
    shortName: "HY",
    textColor: "#1F93CD",
    desgination: "Chairman & Co-founder",
    description: `A distinguished co-founder and esteemed Chairman of Legal Help Squad, brings a wealth of experience from his accomplished tenure as an operations manager in multinational corporations. His portfolio attests to exceptional leadership, strategic insight, and a drive for organizational excellence`,
    facebook: "#",
    twitter: "#",
    instagram: "#",
    boxShadow: "rgba(31, 147, 205, 0.50)",
    circleColor: "rgba(31, 147, 205, 0.18)",
  },

  {
    id: 3,
    image: avatar3,
    name: "Salman Idrees",
    shortName: "SI",
    textColor: "#F6841F",
    desgination: "COO & Board Member",
    description: `Our dynamic Chief Operating Officer leads operational excellence with a visionary approach. Their strategic leadership in process optimisation, cross-functional collaboration, and change management drives our efficiency and innovation, fostering a collaborative work environment.`,
    facebook: "#",
    twitter: "#",
    instagram: "#",
    boxShadow: "rgba(246, 132, 31, 0.28)",
    circleColor: "rgba(252, 180, 52, 0.18)",
  },
  {
    id: 4,
    image: avatar5,
    name: "Nidi Sharma",
    shortName: "NS",
    textColor: "#FCB434",
    desgination: "Safer Recruitment Spacialist",
    description: `Our compassionate safer Recruitment specialist cultivates a\n vibrant company culture and empowers our teams. Their dedication to employee growth,development,\n and well-being fosters a positive work environment,driving our collective success.`,
    facebook: "#",
    twitter: "#",
    instagram: "#",
    boxShadow: "rgba(252, 180, 52, 0.49)",
    circleColor: "rgba(246, 132, 31, 0.18)",
  },
  {
    id: 5,
    image: avatar4,
    name: "Sangeetha Sigamani",
    shortName: "SS",
    textColor: "#F04F41",
    desgination: "Head of children's Well being",
    description: `Our dedicated Head of Children safeguarding and well being, ensures our adherence to regulatory standards and ethical practices. Their meticulous attention to detail and in- depth knowledge of compliance frameworks guarantee our organisation's integrity and credibility.`,
    facebook: "#",
    twitter: "#",
    instagram: "#",
    boxShadow: "rgba(240, 79, 65, 0.37)",
    circleColor: "rgba(240, 79, 65, 0.18)",
  },
  {
    id: 6,
    image: avatar7,
    name: "Parvase Majeed",
    shortName: "PM",
    textColor: "#15AABC",
    desgination: "CFO & Board Member",
    description: `As our esteemed Chief Financial Officer ensures the financial stability and growth of our organisation. Their strategic financial planning and investment expertise drive our fiscal success, while their commitment to ethical financial practices sets a standard for responsible financial stewardship.`,
    facebook: "#",
    twitter: "#",
    instagram: "#",
    boxShadow: "rgba(21, 170, 188, 0.40)",
    circleColor: "rgba(36, 187, 161, 0.18)",
  },
];
